SERVER_PORT: 8081

## DATASOURCE(PSQL)
#PSQL_URL: jdbc:??://localhost:5436/shards?serverTimezone=UTC
#PSQL_USERNAME: root
#PSQL_PASSWORD: 'Abc@123456'
#PSQL_MAX_POOL_SIZE: 100
#PSQL_MINI_IDLE: 10
#PSQL_IDLE_TIMEOUT: 600000
#PSQL_CONNECTION_TIMEOUT: 30000
#PSQL_MAX_LIFE_TIME: 1800000
#PSQL_VALIDATION_TIME: 5000